logger:
  is_json: true
  add_source: false
  level: debug
  set_file: false
  file_name: logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 7

postgres:
  host: postgres
  user: admin
  password: test
  dbname: app_db
  port: 5432
  sslmode: disable
  pool_max_conns: 10
  migrations_dir: file://migrations
  query_timeout: 2000000000 # 2 second

redis:
  addr: redis:6379
  password: auth
  db: 0
  dial_timeout: 5 # second
  read_timeout: 3 # second
  write_timeout: 3 # second
  pool_size: 10
  min_idle_conns: 3
  pool_timeout: 4 # second
  max_retries: 3
  min_retry_backoff: 8 # millisecond
  max_retry_backoff: 512 # millisecond

httpserver:
  host: 127.0.0.1
  port: 50050
  gin_mode: release # debug, test, release
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false