logger:
  is_json: true
  add_source: false
  level: error
  set_file: false
  file_name: logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 7

cookie:
  refresh:
    name: refresh
    max_age: 2592000
    path: / # food.foodgrammbot.ru
    domain: localhost
    secure: true
    http_only: true

bcrypt:
  cost: 10

uid:
  chars: 0123456789ABCDEFHKLMNPQRSTUVWXYZabcdefghkmnpqrstuvwxyz
  count: 32

jwt:
  secret_path: .secret # path to file with secret key
  secret_hash_len: 30
  access_exp_at: 1440 # minutes
  refresh_exp_at: 30 # days

client:
  timeout_req: 60 # second
  openai:
    url: https://food-gpt.foodgrammbot.ru
  payment:
    url: https://payment.foodgrammbot.ru
  recipe_scraper:
    url: http://localhost:50052

websocket:
  payment:
    payment_ws_url: wss://payment.foodgrammbot.ru/ws/check_status_payment

worker:
  life_hack_of_the_day:
    sleep_duration: 1440 # minutes
    timeout: 30 # second
    max_error_count: 3 # max error count

postgres:
  host: postgres
  user: admin
  password: test
  dbname: foodgrammm_db
  port: 5432
  sslmode: disable
  pool_max_conns: 10
  migrations_dir: file://migrations
  query_timeout: 2000000000 # 2 second

redis:
  addr: redis:6379
  password: auth
  db: 0
  dial_timeout: 5 # second
  read_timeout: 3 # second
  write_timeout: 3 # second
  pool_size: 10
  min_idle_conns: 3
  pool_timeout: 4 # second
  max_retries: 3
  min_retry_backoff: 8 # millisecond
  max_retry_backoff: 512 # millisecond

httpserver:
  host: 127.0.0.1
  port: 50050
  gin_mode: release # debug, test, release
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false