// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	parser "github.com/go-jedi/foodgramm_backend/internal/domain/parser"
	mock "github.com/stretchr/testify/mock"

	recipe "github.com/go-jedi/foodgramm_backend/internal/domain/recipe"

	subscription "github.com/go-jedi/foodgramm_backend/internal/domain/subscription"
)

// RecipeRepository is an autogenerated mock type for the RecipeRepository type
type RecipeRepository struct {
	mock.Mock
}

// CreateRecipe provides a mock function with given fields: ctx, accessType, data
func (_m *RecipeRepository) CreateRecipe(ctx context.Context, accessType subscription.AccessType, data parser.ParsedRecipe) (recipe.Recipes, error) {
	ret := _m.Called(ctx, accessType, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 recipe.Recipes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, subscription.AccessType, parser.ParsedRecipe) (recipe.Recipes, error)); ok {
		return rf(ctx, accessType, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, subscription.AccessType, parser.ParsedRecipe) recipe.Recipes); ok {
		r0 = rf(ctx, accessType, data)
	} else {
		r0 = ret.Get(0).(recipe.Recipes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, subscription.AccessType, parser.ParsedRecipe) error); ok {
		r1 = rf(ctx, accessType, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsFreeRecipesByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *RecipeRepository) ExistsFreeRecipesByTelegramID(ctx context.Context, telegramID string) (bool, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsFreeRecipesByTelegramID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFreeRecipesByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *RecipeRepository) GetFreeRecipesByTelegramID(ctx context.Context, telegramID string) (recipe.UserFreeRecipes, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetFreeRecipesByTelegramID")
	}

	var r0 recipe.UserFreeRecipes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (recipe.UserFreeRecipes, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) recipe.UserFreeRecipes); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(recipe.UserFreeRecipes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListRecipesByTelegramID provides a mock function with given fields: ctx, dto
func (_m *RecipeRepository) GetListRecipesByTelegramID(ctx context.Context, dto recipe.GetListRecipesByTelegramIDDTO) (recipe.GetListRecipesByTelegramIDResponse, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for GetListRecipesByTelegramID")
	}

	var r0 recipe.GetListRecipesByTelegramIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, recipe.GetListRecipesByTelegramIDDTO) (recipe.GetListRecipesByTelegramIDResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, recipe.GetListRecipesByTelegramIDDTO) recipe.GetListRecipesByTelegramIDResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(recipe.GetListRecipesByTelegramIDResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, recipe.GetListRecipesByTelegramIDDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipesByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *RecipeRepository) GetRecipesByTelegramID(ctx context.Context, telegramID string) ([]recipe.Recipes, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipesByTelegramID")
	}

	var r0 []recipe.Recipes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]recipe.Recipes, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []recipe.Recipes); ok {
		r0 = rf(ctx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]recipe.Recipes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRecipeRepository creates a new instance of RecipeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecipeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecipeRepository {
	mock := &RecipeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
