// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	recipetypes "github.com/go-jedi/foodgramm_backend/internal/domain/recipe_types"
	mock "github.com/stretchr/testify/mock"
)

// RecipeTypesRepository is an autogenerated mock type for the RecipeTypesRepository type
type RecipeTypesRepository struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *RecipeTypesRepository) All(ctx context.Context) ([]recipetypes.RecipeTypes, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []recipetypes.RecipeTypes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]recipetypes.RecipeTypes, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []recipetypes.RecipeTypes); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]recipetypes.RecipeTypes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, dto
func (_m *RecipeTypesRepository) Create(ctx context.Context, dto recipetypes.CreateDTO) (recipetypes.RecipeTypes, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 recipetypes.RecipeTypes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, recipetypes.CreateDTO) (recipetypes.RecipeTypes, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, recipetypes.CreateDTO) recipetypes.RecipeTypes); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(recipetypes.RecipeTypes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, recipetypes.CreateDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, recipeTypeID
func (_m *RecipeTypesRepository) DeleteByID(ctx context.Context, recipeTypeID int64) (int64, error) {
	ret := _m.Called(ctx, recipeTypeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, recipeTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, recipeTypeID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, recipeTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exists provides a mock function with given fields: ctx, title
func (_m *RecipeTypesRepository) Exists(ctx context.Context, title string) (bool, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, title)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByRecipeTypeID provides a mock function with given fields: ctx, recipeTypeID
func (_m *RecipeTypesRepository) ExistsByRecipeTypeID(ctx context.Context, recipeTypeID int64) (bool, error) {
	ret := _m.Called(ctx, recipeTypeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByRecipeTypeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, recipeTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, recipeTypeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, recipeTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsExceptCurrent provides a mock function with given fields: ctx, recipeTypeID, title
func (_m *RecipeTypesRepository) ExistsExceptCurrent(ctx context.Context, recipeTypeID int64, title string) (bool, error) {
	ret := _m.Called(ctx, recipeTypeID, title)

	if len(ret) == 0 {
		panic("no return value specified for ExistsExceptCurrent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return rf(ctx, recipeTypeID, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, recipeTypeID, title)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, recipeTypeID, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, recipeTypeID
func (_m *RecipeTypesRepository) GetByID(ctx context.Context, recipeTypeID int64) (recipetypes.RecipeTypes, error) {
	ret := _m.Called(ctx, recipeTypeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 recipetypes.RecipeTypes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (recipetypes.RecipeTypes, error)); ok {
		return rf(ctx, recipeTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) recipetypes.RecipeTypes); ok {
		r0 = rf(ctx, recipeTypeID)
	} else {
		r0 = ret.Get(0).(recipetypes.RecipeTypes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, recipeTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, dto
func (_m *RecipeTypesRepository) Update(ctx context.Context, dto recipetypes.UpdateDTO) (recipetypes.RecipeTypes, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 recipetypes.RecipeTypes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, recipetypes.UpdateDTO) (recipetypes.RecipeTypes, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, recipetypes.UpdateDTO) recipetypes.RecipeTypes); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(recipetypes.RecipeTypes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, recipetypes.UpdateDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRecipeTypesRepository creates a new instance of RecipeTypesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecipeTypesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecipeTypesRepository {
	mock := &RecipeTypesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
