// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/go-jedi/foodgramm_backend/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, dto
func (_m *AuthService) Check(ctx context.Context, dto auth.CheckDTO) (auth.CheckResponse, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 auth.CheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.CheckDTO) (auth.CheckResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.CheckDTO) auth.CheckResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(auth.CheckResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.CheckDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: ctx, dto
func (_m *AuthService) Refresh(ctx context.Context, dto auth.RefreshDTO) (auth.RefreshResponse, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 auth.RefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshDTO) (auth.RefreshResponse, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RefreshDTO) auth.RefreshResponse); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(auth.RefreshResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RefreshDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignIn provides a mock function with given fields: ctx, dto
func (_m *AuthService) SignIn(ctx context.Context, dto auth.SignInDTO) (auth.SignInResp, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 auth.SignInResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.SignInDTO) (auth.SignInResp, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.SignInDTO) auth.SignInResp); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(auth.SignInResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.SignInDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
