// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	templates "github.com/go-jedi/foodgramm_backend/internal/domain/templates"
)

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

// Generate provides a mock function with no fields
func (_m *ITemplate) Generate() (templates.ApplyDataToTemplateResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 templates.ApplyDataToTemplateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (templates.ApplyDataToTemplateResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() templates.ApplyDataToTemplateResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(templates.ApplyDataToTemplateResponse)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITemplate creates a new instance of ITemplate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITemplate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITemplate {
	mock := &ITemplate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
