// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	parser "github.com/go-jedi/foodgrammm-backend/internal/domain/parser"
	mock "github.com/stretchr/testify/mock"
)

// IParser is an autogenerated mock type for the IParser type
type IParser struct {
	mock.Mock
}

// ParseRecipe provides a mock function with given fields: telegramID, input
func (_m *IParser) ParseRecipe(telegramID string, input string) (parser.ParsedRecipe, error) {
	ret := _m.Called(telegramID, input)

	if len(ret) == 0 {
		panic("no return value specified for ParseRecipe")
	}

	var r0 parser.ParsedRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (parser.ParsedRecipe, error)); ok {
		return rf(telegramID, input)
	}
	if rf, ok := ret.Get(0).(func(string, string) parser.ParsedRecipe); ok {
		r0 = rf(telegramID, input)
	} else {
		r0 = ret.Get(0).(parser.ParsedRecipe)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(telegramID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIParser creates a new instance of IParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *IParser {
	mock := &IParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
