// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	recipe "github.com/go-jedi/foodgramm_backend/internal/templates/recipe"
	mock "github.com/stretchr/testify/mock"
)

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

// Generate provides a mock function with given fields: data
func (_m *ITemplate) Generate(data recipe.GenerateRecipe) (string, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(recipe.GenerateRecipe) (string, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(recipe.GenerateRecipe) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(recipe.GenerateRecipe) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITemplate creates a new instance of ITemplate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITemplate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITemplate {
	mock := &ITemplate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
