basePath: /v1
host: localhost:50050
info:
  contact: {}
  description: This is a application for telegram web apps application.
  title: API application for telegram web apps application foodgrammm
  version: "1.0"
paths:
  /ping:
    get:
      description: Check server status
      produces:
      - application/json
      responses:
        "200":
          description: 'message: pong'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping
      tags:
      - Health
swagger: "2.0"
