basePath: /v1
host: localhost:50050
info:
  contact: {}
  description: This is a application for telegram web apps application.
  title: API application for telegram web apps application foodgrammm
  version: "1.0"
paths: {}
swagger: "2.0"
